language: python

python:
 - "3.6"

    
install:    
- pip install -r requirements.txt

env: 
  - APP_SETTINGS='development'
  
script:
  - pytest

script: 
  - py.test --cov-report term --cov=app/tests/
  
after_success:
  - codecov
